### ISSUE TITLE
The lack of dataset

### ISSUE THREAD

**Issue by LauraSanchz2** [ICTMCG/Pref-FEND#1]
Dear Zhang Xue Yao: I am a master student in SEU, and my research derection is in line with yours.Your paper "Pref-FEND"is quite well-wirtten, and I want to reproduce the result in this article. But I can't find the dataset refered in the article .I will appreciate it if you can kindly send me the dataset(including social media posts and relevant articles, named "Weibo Dataset" and "Twitter Dataset").I assure you that the dataset is for academic use only.Thanks so much~!

**Comment by sheng-qiang** [comment]
You may fill out an application form (https://forms.office.com/r/HF00qdb3Zk) and our datasets will send via email. We are still preparing the release and will send them in a few days.

**Comment by LauraSanchz2** [comment]
> You may fill out an application form (https://forms.office.com/r/HF00qdb3Zk) and our datasets will send via email. We are still preparing the release and will send them in a few days.

Thank you so  much!
